from .games.brain_calc import generate_question as generate_question_calc
from .games.brain_even import generate_question as generate_question_even
from .games.brain_gcd import generate_question as generate_question_gcd
from .games.brain_prime import generate_question as generate_question_prime
from .games.brain_prog import generate_question as generate_question_prog

generate_question_calc
generate_question_even
generate_question_gcd
generate_question_prime
generate_question_prog
