from .games.brain_calc_init import generate_question as generate_question_calc
from .games.brain_even_init import generate_question as generate_question_even
from .games.brain_gcd_init import generate_question as generate_question_gcd
from .games.brain_prime_init import generate_question as generate_question_prime
from .games.brain_progression_init import generate_question as generate_question_progression